name: Run 701 Check with HAP

on:
  schedule:
    - cron: '0 4-22 * * *'
    - cron: '30 4-22 * * *'
  workflow_dispatch:              # Manual trigger from the GitHub UI

jobs:
  run-check:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run 701_check
        run: |
          $env:DISCORD_WEBHOOK = "${{ secrets.DISCORD_WEBHOOK }}"
          ./bin/Release/net8.0/701_check.exe
